standard_gates_commutations = {
    ("t", "tdg"): True,
    ("t", "s"): True,
    ("t", "h"): False,
    ("t", "id"): True,
    ("t", "sx"): False,
    ("t", "sxdg"): False,
    ("t", "x"): False,
    ("t", "rccx"): {
        (0,): True,
        (1,): True,
        (2,): False,
    },
    ("t", "rcccx"): {
        (0,): True,
        (1,): True,
        (2,): True,
        (3,): False,
    },
    ("t", "ecr"): False,
    ("t", "swap"): False,
    ("t", "y"): False,
    ("t", "z"): True,
    ("t", "cx"): {
        (0,): True,
        (1,): False,
    },
    ("t", "ccx"): {
        (0,): True,
        (1,): True,
        (2,): False,
    },
    ("t", "mcx"): {
        (0,): True,
        (1,): True,
        (2,): True,
        (3,): False,
    },
    ("t", "cswap"): {
        (0,): True,
        (1,): False,
        (2,): False,
    },
    ("t", "cy"): {
        (0,): True,
        (1,): False,
    },
    ("t", "cz"): True,
    ("tdg", "s"): True,
    ("tdg", "id"): True,
    ("tdg", "sx"): False,
    ("tdg", "x"): False,
    ("tdg", "rccx"): {
        (0,): True,
        (1,): True,
        (2,): False,
    },
    ("tdg", "rcccx"): {
        (0,): True,
        (1,): True,
        (2,): True,
        (3,): False,
    },
    ("tdg", "cx"): {
        (0,): True,
        (1,): False,
    },
    ("tdg", "mcx"): {
        (0,): True,
        (1,): True,
        (2,): True,
        (3,): False,
    },
    ("tdg", "cy"): {
        (0,): True,
        (1,): False,
    },
    ("s", "id"): True,
    ("s", "sx"): False,
    ("s", "x"): False,
    ("s", "rccx"): {
        (0,): True,
        (1,): True,
        (2,): False,
    },
    ("s", "rcccx"): {
        (0,): True,
        (1,): True,
        (2,): True,
        (3,): False,
    },
    ("s", "cx"): {
        (0,): True,
        (1,): False,
    },
    ("s", "mcx"): {
        (0,): True,
        (1,): True,
        (2,): True,
        (3,): False,
    },
    ("s", "cy"): {
        (0,): True,
        (1,): False,
    },
    ("sdg", "t"): True,
    ("sdg", "tdg"): True,
    ("sdg", "s"): True,
    ("sdg", "h"): False,
    ("sdg", "id"): True,
    ("sdg", "sx"): False,
    ("sdg", "sxdg"): False,
    ("sdg", "x"): False,
    ("sdg", "rccx"): {
        (0,): True,
        (1,): True,
        (2,): False,
    },
    ("sdg", "rcccx"): {
        (0,): True,
        (1,): True,
        (2,): True,
        (3,): False,
    },
    ("sdg", "ecr"): False,
    ("sdg", "swap"): False,
    ("sdg", "iswap"): False,
    ("sdg", "dcx"): False,
    ("sdg", "y"): False,
    ("sdg", "z"): True,
    ("sdg", "ch"): {
        (0,): True,
        (1,): False,
    },
    ("sdg", "csx"): {
        (0,): True,
        (1,): False,
    },
    ("sdg", "cx"): {
        (0,): True,
        (1,): False,
    },
    ("sdg", "ccx"): {
        (0,): True,
        (1,): True,
        (2,): False,
    },
    ("sdg", "mcx"): {
        (0,): True,
        (1,): True,
        (2,): True,
        (3,): False,
    },
    ("sdg", "cswap"): {
        (0,): True,
        (1,): False,
        (2,): False,
    },
    ("sdg", "cy"): {
        (0,): True,
        (1,): False,
    },
    ("sdg", "cz"): True,
    ("h", "tdg"): False,
    ("h", "s"): False,
    ("h", "id"): True,
    ("h", "sx"): False,
    ("h", "sxdg"): False,
    ("h", "x"): False,
    ("h", "rccx"): False,
    ("h", "rcccx"): False,
    ("h", "ecr"): False,
    ("h", "y"): False,
    ("h", "z"): False,
    ("h", "cx"): False,
    ("h", "ccx"): False,
    ("h", "mcx"): False,
    ("h", "cswap"): False,
    ("h", "cy"): False,
    ("id", "rcccx"): True,
    ("id", "mcx"): True,
    ("id", "cy"): True,
    ("sx", "id"): True,
    ("sx", "rcccx"): False,
    ("sx", "mcx"): {
        (0,): False,
        (1,): False,
        (2,): False,
        (3,): True,
    },
    ("sx", "cy"): False,
    ("sxdg", "tdg"): False,
    ("sxdg", "s"): False,
    ("sxdg", "id"): True,
    ("sxdg", "sx"): True,
    ("sxdg", "x"): True,
    ("sxdg", "rccx"): False,
    ("sxdg", "rcccx"): False,
    ("sxdg", "cx"): {
        (0,): False,
        (1,): True,
    },
    ("sxdg", "mcx"): {
        (0,): False,
        (1,): False,
        (2,): False,
        (3,): True,
    },
    ("sxdg", "cy"): False,
    ("x", "id"): True,
    ("x", "sx"): True,
    ("x", "rcccx"): False,
    ("x", "mcx"): {
        (0,): False,
        (1,): False,
        (2,): False,
        (3,): True,
    },
    ("x", "cy"): False,
    ("rccx", "id"): True,
    ("rccx", "sx"): False,
    ("rccx", "x"): False,
    ("rccx", "rcccx"): {
        (0, 1, 2): False,
        (0, 1, 3): False,
        (0, 1, None): True,
        (0, 2, 1): False,
        (0, 2, 3): True,
        (0, 2, None): True,
        (0, 3, 1): False,
        (0, 3, 2): False,
        (0, 3, None): False,
        (0, None, 1): False,
        (0, None, 2): False,
        (0, None, 3): False,
        (0, None, None): True,
        (1, 0, 2): False,
        (1, 0, 3): False,
        (1, 0, None): True,
        (1, 2, 0): False,
        (1, 2, 3): True,
        (1, 2, None): True,
        (1, 3, 0): False,
        (1, 3, 2): False,
        (1, 3, None): False,
        (1, None, 0): False,
        (1, None, 2): False,
        (1, None, 3): False,
        (1, None, None): True,
        (2, 0, 1): False,
        (2, 0, 3): True,
        (2, 0, None): True,
        (2, 1, 0): False,
        (2, 1, 3): True,
        (2, 1, None): True,
        (2, 3, 0): False,
        (2, 3, 1): False,
        (2, 3, None): False,
        (2, None, 0): False,
        (2, None, 1): False,
        (2, None, 3): False,
        (2, None, None): True,
        (3, 0, 1): False,
        (3, 0, 2): False,
        (3, 0, None): False,
        (3, 1, 0): False,
        (3, 1, 2): False,
        (3, 1, None): False,
        (3, 2, 0): False,
        (3, 2, 1): False,
        (3, 2, None): False,
        (3, None, 0): False,
        (3, None, 1): False,
        (3, None, 2): False,
        (3, None, None): False,
        (None, 0, 1): False,
        (None, 0, 2): False,
        (None, 0, 3): False,
        (None, 0, None): True,
        (None, 1, 0): False,
        (None, 1, 2): False,
        (None, 1, 3): False,
        (None, 1, None): True,
        (None, 2, 0): False,
        (None, 2, 1): False,
        (None, 2, 3): True,
        (None, 2, None): True,
        (None, 3, 0): False,
        (None, 3, 1): False,
        (None, 3, 2): False,
        (None, 3, None): False,
        (None, None, 0): False,
        (None, None, 1): False,
        (None, None, 2): False,
        (None, None, 3): False,
    },
    ("rccx", "mcx"): {
        (0, 1, 2): False,
        (0, 1, 3): False,
        (0, 1, None): True,
        (0, 2, 1): False,
        (0, 2, 3): False,
        (0, 2, None): True,
        (0, 3, 1): False,
        (0, 3, 2): False,
        (0, 3, None): False,
        (0, None, 1): False,
        (0, None, 2): False,
        (0, None, 3): False,
        (0, None, None): True,
        (1, 0, 2): False,
        (1, 0, 3): False,
        (1, 0, None): True,
        (1, 2, 0): False,
        (1, 2, 3): False,
        (1, 2, None): True,
        (1, 3, 0): False,
        (1, 3, 2): False,
        (1, 3, None): False,
        (1, None, 0): False,
        (1, None, 2): False,
        (1, None, 3): False,
        (1, None, None): True,
        (2, 0, 1): False,
        (2, 0, 3): False,
        (2, 0, None): True,
        (2, 1, 0): False,
        (2, 1, 3): False,
        (2, 1, None): True,
        (2, 3, 0): False,
        (2, 3, 1): False,
        (2, 3, None): False,
        (2, None, 0): False,
        (2, None, 1): False,
        (2, None, 3): False,
        (2, None, None): True,
        (3, 0, 1): False,
        (3, 0, 2): False,
        (3, 0, None): False,
        (3, 1, 0): False,
        (3, 1, 2): False,
        (3, 1, None): False,
        (3, 2, 0): False,
        (3, 2, 1): False,
        (3, 2, None): False,
        (3, None, 0): False,
        (3, None, 1): False,
        (3, None, 2): False,
        (3, None, None): False,
        (None, 0, 1): False,
        (None, 0, 2): False,
        (None, 0, 3): False,
        (None, 0, None): True,
        (None, 1, 0): False,
        (None, 1, 2): False,
        (None, 1, 3): False,
        (None, 1, None): True,
        (None, 2, 0): False,
        (None, 2, 1): False,
        (None, 2, 3): False,
        (None, 2, None): True,
        (None, 3, 0): False,
        (None, 3, 1): False,
        (None, 3, 2): False,
        (None, 3, None): False,
        (None, None, 0): False,
        (None, None, 1): False,
        (None, None, 2): False,
        (None, None, 3): False,
    },
    ("rccx", "cy"): {
        (0, 1, None): False,
        (0, None, 1): False,
        (0, None, None): True,
        (1, 0, None): False,
        (1, None, 0): False,
        (1, None, None): False,
        (None, 0, 1): True,
        (None, 0, None): True,
        (None, 1, 0): False,
        (None, 1, None): False,
        (None, None, 0): False,
        (None, None, 1): False,
    },
    ("ecr", "tdg"): False,
    ("ecr", "s"): False,
    ("ecr", "id"): True,
    ("ecr", "sx"): {
        (0, None): False,
        (None, 0): True,
    },
    ("ecr", "sxdg"): {
        (0, None): False,
        (None, 0): True,
    },
    ("ecr", "x"): {
        (0, None): False,
        (None, 0): True,
    },
    ("ecr", "rccx"): False,
    ("ecr", "rcccx"): False,
    ("ecr", "y"): False,
    ("ecr", "z"): False,
    ("ecr", "cx"): {
        (0, 1): False,
        (0, None): False,
        (1, 0): False,
        (1, None): False,
        (None, 0): False,
        (None, 1): True,
    },
    ("ecr", "ccx"): {
        (0, 1): False,
        (0, 2): False,
        (0, None): False,
        (1, 0): False,
        (1, 2): False,
        (1, None): False,
        (2, 0): False,
        (2, 1): False,
        (2, None): False,
        (None, 0): False,
        (None, 1): False,
        (None, 2): True,
    },
    ("ecr", "mcx"): {
        (0, 1): False,
        (0, 2): False,
        (0, 3): False,
        (0, None): False,
        (1, 0): False,
        (1, 2): False,
        (1, 3): False,
        (1, None): False,
        (2, 0): False,
        (2, 1): False,
        (2, 3): False,
        (2, None): False,
        (3, 0): False,
        (3, 1): False,
        (3, 2): False,
        (3, None): False,
        (None, 0): False,
        (None, 1): False,
        (None, 2): False,
        (None, 3): True,
    },
    ("ecr", "cy"): False,
    ("swap", "tdg"): False,
    ("swap", "s"): False,
    ("swap", "h"): False,
    ("swap", "id"): True,
    ("swap", "sx"): False,
    ("swap", "sxdg"): False,
    ("swap", "x"): False,
    ("swap", "rccx"): False,
    ("swap", "rcccx"): {
        (0, 1): True,
        (0, 2): False,
        (0, 3): False,
        (0, None): False,
        (1, 0): True,
        (1, 2): False,
        (1, 3): False,
        (1, None): False,
        (2, 0): False,
        (2, 1): False,
        (2, 3): False,
        (2, None): False,
        (3, 0): False,
        (3, 1): False,
        (3, 2): False,
        (3, None): False,
        (None, 0): False,
        (None, 1): False,
        (None, 2): False,
        (None, 3): False,
    },
    ("swap", "ecr"): False,
    ("swap", "y"): False,
    ("swap", "z"): False,
    ("swap", "cx"): False,
    ("swap", "ccx"): {
        (0, 1): True,
        (0, 2): False,
        (0, None): False,
        (1, 0): True,
        (1, 2): False,
        (1, None): False,
        (2, 0): False,
        (2, 1): False,
        (2, None): False,
        (None, 0): False,
        (None, 1): False,
        (None, 2): False,
    },
    ("swap", "mcx"): {
        (0, 1): True,
        (0, 2): True,
        (0, 3): False,
        (0, None): False,
        (1, 0): True,
        (1, 2): True,
        (1, 3): False,
        (1, None): False,
        (2, 0): True,
        (2, 1): True,
        (2, 3): False,
        (2, None): False,
        (3, 0): False,
        (3, 1): False,
        (3, 2): False,
        (3, None): False,
        (None, 0): False,
        (None, 1): False,
        (None, 2): False,
        (None, 3): False,
    },
    ("swap", "cswap"): {
        (0, 1): False,
        (0, 2): False,
        (0, None): False,
        (1, 0): False,
        (1, 2): True,
        (1, None): False,
        (2, 0): False,
        (2, 1): True,
        (2, None): False,
        (None, 0): False,
        (None, 1): False,
        (None, 2): False,
    },
    ("swap", "cy"): False,
    ("swap", "cz"): {
        (0, 1): True,
        (0, None): False,
        (1, 0): True,
        (1, None): False,
        (None, 0): False,
        (None, 1): False,
    },
    ("iswap", "t"): False,
    ("iswap", "tdg"): False,
    ("iswap", "s"): False,
    ("iswap", "h"): False,
    ("iswap", "id"): True,
    ("iswap", "sx"): False,
    ("iswap", "sxdg"): False,
    ("iswap", "x"): False,
    ("iswap", "rccx"): False,
    ("iswap", "rcccx"): {
        (0, 1): True,
        (0, 2): False,
        (0, 3): False,
        (0, None): False,
        (1, 0): True,
        (1, 2): False,
        (1, 3): False,
        (1, None): False,
        (2, 0): False,
        (2, 1): False,
        (2, 3): False,
        (2, None): False,
        (3, 0): False,
        (3, 1): False,
        (3, 2): False,
        (3, None): False,
        (None, 0): False,
        (None, 1): False,
        (None, 2): False,
        (None, 3): False,
    },
    ("iswap", "ecr"): False,
    ("iswap", "swap"): {
        (0, 1): True,
        (0, None): False,
        (1, 0): True,
        (1, None): False,
        (None, 0): False,
        (None, 1): False,
    },
    ("iswap", "y"): False,
    ("iswap", "z"): False,
    ("iswap", "cx"): False,
    ("iswap", "ccx"): {
        (0, 1): True,
        (0, 2): False,
        (0, None): False,
        (1, 0): True,
        (1, 2): False,
        (1, None): False,
        (2, 0): False,
        (2, 1): False,
        (2, None): False,
        (None, 0): False,
        (None, 1): False,
        (None, 2): False,
    },
    ("iswap", "mcx"): {
        (0, 1): True,
        (0, 2): True,
        (0, 3): False,
        (0, None): False,
        (1, 0): True,
        (1, 2): True,
        (1, 3): False,
        (1, None): False,
        (2, 0): True,
        (2, 1): True,
        (2, 3): False,
        (2, None): False,
        (3, 0): False,
        (3, 1): False,
        (3, 2): False,
        (3, None): False,
        (None, 0): False,
        (None, 1): False,
        (None, 2): False,
        (None, 3): False,
    },
    ("iswap", "cswap"): {
        (0, 1): False,
        (0, 2): False,
        (0, None): False,
        (1, 0): False,
        (1, 2): True,
        (1, None): False,
        (2, 0): False,
        (2, 1): True,
        (2, None): False,
        (None, 0): False,
        (None, 1): False,
        (None, 2): False,
    },
    ("iswap", "cy"): False,
    ("iswap", "cz"): {
        (0, 1): True,
        (0, None): False,
        (1, 0): True,
        (1, None): False,
        (None, 0): False,
        (None, 1): False,
    },
    ("dcx", "t"): False,
    ("dcx", "tdg"): False,
    ("dcx", "s"): False,
    ("dcx", "h"): False,
    ("dcx", "id"): True,
    ("dcx", "sx"): False,
    ("dcx", "sxdg"): False,
    ("dcx", "x"): False,
    ("dcx", "rccx"): False,
    ("dcx", "rcccx"): False,
    ("dcx", "ecr"): False,
    ("dcx", "swap"): False,
    ("dcx", "iswap"): False,
    ("dcx", "y"): False,
    ("dcx", "z"): False,
    ("dcx", "ch"): False,
    ("dcx", "csx"): False,
    ("dcx", "cx"): False,
    ("dcx", "ccx"): False,
    ("dcx", "mcx"): False,
    ("dcx", "cswap"): False,
    ("dcx", "cy"): False,
    ("dcx", "cz"): False,
    ("y", "tdg"): False,
    ("y", "s"): False,
    ("y", "id"): True,
    ("y", "sx"): False,
    ("y", "sxdg"): False,
    ("y", "x"): False,
    ("y", "rccx"): False,
    ("y", "rcccx"): False,
    ("y", "z"): False,
    ("y", "cx"): False,
    ("y", "mcx"): False,
    ("y", "cy"): {
        (0,): False,
        (1,): True,
    },
    ("z", "tdg"): True,
    ("z", "s"): True,
    ("z", "id"): True,
    ("z", "sx"): False,
    ("z", "sxdg"): False,
    ("z", "x"): False,
    ("z", "rccx"): {
        (0,): True,
        (1,): True,
        (2,): False,
    },
    ("z", "rcccx"): {
        (0,): True,
        (1,): True,
        (2,): True,
        (3,): False,
    },
    ("z", "cx"): {
        (0,): True,
        (1,): False,
    },
    ("z", "mcx"): {
        (0,): True,
        (1,): True,
        (2,): True,
        (3,): False,
    },
    ("z", "cy"): {
        (0,): True,
        (1,): False,
    },
    ("ch", "t"): {
        (0, None): True,
        (None, 0): False,
    },
    ("ch", "tdg"): {
        (0, None): True,
        (None, 0): False,
    },
    ("ch", "s"): {
        (0, None): True,
        (None, 0): False,
    },
    ("ch", "h"): {
        (0, None): False,
        (None, 0): True,
    },
    ("ch", "id"): True,
    ("ch", "sx"): False,
    ("ch", "sxdg"): False,
    ("ch", "x"): False,
    ("ch", "rccx"): {
        (0, 1): False,
        (0, 2): False,
        (0, None): True,
        (1, 0): False,
        (1, 2): False,
        (1, None): True,
        (2, 0): False,
        (2, 1): False,
        (2, None): False,
        (None, 0): False,
        (None, 1): False,
        (None, 2): False,
    },
    ("ch", "rcccx"): {
        (0, 1): False,
        (0, 2): False,
        (0, 3): False,
        (0, None): True,
        (1, 0): False,
        (1, 2): False,
        (1, 3): False,
        (1, None): True,
        (2, 0): False,
        (2, 1): False,
        (2, 3): False,
        (2, None): True,
        (3, 0): False,
        (3, 1): False,
        (3, 2): False,
        (3, None): False,
        (None, 0): False,
        (None, 1): False,
        (None, 2): False,
        (None, 3): False,
    },
    ("ch", "ecr"): False,
    ("ch", "swap"): False,
    ("ch", "iswap"): False,
    ("ch", "y"): False,
    ("ch", "z"): {
        (0, None): True,
        (None, 0): False,
    },
    ("ch", "cx"): {
        (0, 1): False,
        (0, None): True,
        (1, 0): False,
        (1, None): False,
        (None, 0): False,
        (None, 1): False,
    },
    ("ch", "ccx"): {
        (0, 1): False,
        (0, 2): False,
        (0, None): True,
        (1, 0): False,
        (1, 2): False,
        (1, None): True,
        (2, 0): False,
        (2, 1): False,
        (2, None): False,
        (None, 0): False,
        (None, 1): False,
        (None, 2): False,
    },
    ("ch", "mcx"): {
        (0, 1): False,
        (0, 2): False,
        (0, 3): False,
        (0, None): True,
        (1, 0): False,
        (1, 2): False,
        (1, 3): False,
        (1, None): True,
        (2, 0): False,
        (2, 1): False,
        (2, 3): False,
        (2, None): True,
        (3, 0): False,
        (3, 1): False,
        (3, 2): False,
        (3, None): False,
        (None, 0): False,
        (None, 1): False,
        (None, 2): False,
        (None, 3): False,
    },
    ("ch", "cswap"): {
        (0, 1): False,
        (0, 2): False,
        (0, None): True,
        (1, 0): False,
        (1, 2): False,
        (1, None): False,
        (2, 0): False,
        (2, 1): False,
        (2, None): False,
        (None, 0): False,
        (None, 1): False,
        (None, 2): False,
    },
    ("ch", "cy"): {
        (0, 1): False,
        (0, None): True,
        (1, 0): False,
        (1, None): False,
        (None, 0): False,
        (None, 1): False,
    },
    ("ch", "cz"): {
        (0, 1): False,
        (0, None): True,
        (1, 0): False,
        (1, None): True,
        (None, 0): False,
        (None, 1): False,
    },
    ("csx", "t"): {
        (0, None): True,
        (None, 0): False,
    },
    ("csx", "tdg"): {
        (0, None): True,
        (None, 0): False,
    },
    ("csx", "s"): {
        (0, None): True,
        (None, 0): False,
    },
    ("csx", "h"): False,
    ("csx", "id"): True,
    ("csx", "sx"): {
        (0, None): False,
        (None, 0): True,
    },
    ("csx", "sxdg"): {
        (0, None): False,
        (None, 0): True,
    },
    ("csx", "x"): {
        (0, None): False,
        (None, 0): True,
    },
    ("csx", "rccx"): {
        (0, 1): False,
        (0, 2): False,
        (0, None): True,
        (1, 0): False,
        (1, 2): False,
        (1, None): True,
        (2, 0): False,
        (2, 1): False,
        (2, None): False,
        (None, 0): False,
        (None, 1): False,
        (None, 2): False,
    },
    ("csx", "rcccx"): {
        (0, 1): False,
        (0, 2): False,
        (0, 3): False,
        (0, None): True,
        (1, 0): False,
        (1, 2): False,
        (1, 3): False,
        (1, None): True,
        (2, 0): False,
        (2, 1): False,
        (2, 3): False,
        (2, None): True,
        (3, 0): False,
        (3, 1): False,
        (3, 2): False,
        (3, None): False,
        (None, 0): False,
        (None, 1): False,
        (None, 2): False,
        (None, 3): False,
    },
    ("csx", "ecr"): {
        (0, 1): False,
        (0, None): False,
        (1, 0): False,
        (1, None): False,
        (None, 0): False,
        (None, 1): True,
    },
    ("csx", "swap"): False,
    ("csx", "iswap"): False,
    ("csx", "y"): False,
    ("csx", "z"): {
        (0, None): True,
        (None, 0): False,
    },
    ("csx", "ch"): {
        (0, 1): False,
        (0, None): True,
        (1, 0): False,
        (1, None): False,
        (None, 0): False,
        (None, 1): False,
    },
    ("csx", "cx"): {
        (0, 1): True,
        (0, None): True,
        (1, 0): False,
        (1, None): False,
        (None, 0): False,
        (None, 1): True,
    },
    ("csx", "ccx"): {
        (0, 1): False,
        (0, 2): True,
        (0, None): True,
        (1, 0): False,
        (1, 2): True,
        (1, None): True,
        (2, 0): False,
        (2, 1): False,
        (2, None): False,
        (None, 0): False,
        (None, 1): False,
        (None, 2): True,
    },
    ("csx", "mcx"): {
        (0, 1): False,
        (0, 2): False,
        (0, 3): True,
        (0, None): True,
        (1, 0): False,
        (1, 2): False,
        (1, 3): True,
        (1, None): True,
        (2, 0): False,
        (2, 1): False,
        (2, 3): True,
        (2, None): True,
        (3, 0): False,
        (3, 1): False,
        (3, 2): False,
        (3, None): False,
        (None, 0): False,
        (None, 1): False,
        (None, 2): False,
        (None, 3): True,
    },
    ("csx", "cswap"): {
        (0, 1): False,
        (0, 2): False,
        (0, None): True,
        (1, 0): False,
        (1, 2): False,
        (1, None): False,
        (2, 0): False,
        (2, 1): False,
        (2, None): False,
        (None, 0): False,
        (None, 1): False,
        (None, 2): False,
    },
    ("csx", "cy"): {
        (0, 1): False,
        (0, None): True,
        (1, 0): False,
        (1, None): False,
        (None, 0): False,
        (None, 1): False,
    },
    ("csx", "cz"): {
        (0, 1): False,
        (0, None): True,
        (1, 0): False,
        (1, None): True,
        (None, 0): False,
        (None, 1): False,
    },
    ("cx", "id"): True,
    ("cx", "sx"): {
        (0, None): False,
        (None, 0): True,
    },
    ("cx", "x"): {
        (0, None): False,
        (None, 0): True,
    },
    ("cx", "rccx"): {
        (0, 1): False,
        (0, 2): False,
        (0, None): True,
        (1, 0): False,
        (1, 2): False,
        (1, None): True,
        (2, 0): False,
        (2, 1): False,
        (2, None): False,
        (None, 0): False,
        (None, 1): False,
        (None, 2): False,
    },
    ("cx", "rcccx"): {
        (0, 1): False,
        (0, 2): False,
        (0, 3): False,
        (0, None): True,
        (1, 0): False,
        (1, 2): False,
        (1, 3): False,
        (1, None): True,
        (2, 0): False,
        (2, 1): False,
        (2, 3): False,
        (2, None): True,
        (3, 0): False,
        (3, 1): False,
        (3, 2): False,
        (3, None): False,
        (None, 0): False,
        (None, 1): False,
        (None, 2): False,
        (None, 3): False,
    },
    ("cx", "mcx"): {
        (0, 1): False,
        (0, 2): False,
        (0, 3): True,
        (0, None): True,
        (1, 0): False,
        (1, 2): False,
        (1, 3): True,
        (1, None): True,
        (2, 0): False,
        (2, 1): False,
        (2, 3): True,
        (2, None): True,
        (3, 0): False,
        (3, 1): False,
        (3, 2): False,
        (3, None): False,
        (None, 0): False,
        (None, 1): False,
        (None, 2): False,
        (None, 3): True,
    },
    ("cx", "cy"): {
        (0, 1): False,
        (0, None): True,
        (1, 0): False,
        (1, None): False,
        (None, 0): False,
        (None, 1): False,
    },
    ("ccx", "tdg"): {
        (0, None, None): True,
        (None, 0, None): True,
        (None, None, 0): False,
    },
    ("ccx", "s"): {
        (0, None, None): True,
        (None, 0, None): True,
        (None, None, 0): False,
    },
    ("ccx", "id"): True,
    ("ccx", "sx"): {
        (0, None, None): False,
        (None, 0, None): False,
        (None, None, 0): True,
    },
    ("ccx", "sxdg"): {
        (0, None, None): False,
        (None, 0, None): False,
        (None, None, 0): True,
    },
    ("ccx", "x"): {
        (0, None, None): False,
        (None, 0, None): False,
        (None, None, 0): True,
    },
    ("ccx", "rccx"): {
        (0, 1, 2): False,
        (0, 1, None): True,
        (0, 2, 1): False,
        (0, 2, None): False,
        (0, None, 1): False,
        (0, None, 2): False,
        (0, None, None): True,
        (1, 0, 2): False,
        (1, 0, None): True,
        (1, 2, 0): False,
        (1, 2, None): False,
        (1, None, 0): False,
        (1, None, 2): False,
        (1, None, None): True,
        (2, 0, 1): False,
        (2, 0, None): False,
        (2, 1, 0): False,
        (2, 1, None): False,
        (2, None, 0): False,
        (2, None, 1): False,
        (2, None, None): False,
        (None, 0, 1): False,
        (None, 0, 2): False,
        (None, 0, None): True,
        (None, 1, 0): False,
        (None, 1, 2): False,
        (None, 1, None): True,
        (None, 2, 0): False,
        (None, 2, 1): False,
        (None, 2, None): False,
        (None, None, 0): False,
        (None, None, 1): False,
        (None, None, 2): False,
    },
    ("ccx", "rcccx"): {
        (0, 1, 2): False,
        (0, 1, 3): False,
        (0, 1, None): True,
        (0, 2, 1): False,
        (0, 2, 3): False,
        (0, 2, None): True,
        (0, 3, 1): False,
        (0, 3, 2): False,
        (0, 3, None): False,
        (0, None, 1): False,
        (0, None, 2): False,
        (0, None, 3): False,
        (0, None, None): True,
        (1, 0, 2): False,
        (1, 0, 3): False,
        (1, 0, None): True,
        (1, 2, 0): False,
        (1, 2, 3): False,
        (1, 2, None): True,
        (1, 3, 0): False,
        (1, 3, 2): False,
        (1, 3, None): False,
        (1, None, 0): False,
        (1, None, 2): False,
        (1, None, 3): False,
        (1, None, None): True,
        (2, 0, 1): False,
        (2, 0, 3): False,
        (2, 0, None): True,
        (2, 1, 0): False,
        (2, 1, 3): False,
        (2, 1, None): True,
        (2, 3, 0): False,
        (2, 3, 1): False,
        (2, 3, None): False,
        (2, None, 0): False,
        (2, None, 1): False,
        (2, None, 3): False,
        (2, None, None): True,
        (3, 0, 1): False,
        (3, 0, 2): False,
        (3, 0, None): False,
        (3, 1, 0): False,
        (3, 1, 2): False,
        (3, 1, None): False,
        (3, 2, 0): False,
        (3, 2, 1): False,
        (3, 2, None): False,
        (3, None, 0): False,
        (3, None, 1): False,
        (3, None, 2): False,
        (3, None, None): False,
        (None, 0, 1): False,
        (None, 0, 2): False,
        (None, 0, 3): False,
        (None, 0, None): True,
        (None, 1, 0): False,
        (None, 1, 2): False,
        (None, 1, 3): False,
        (None, 1, None): True,
        (None, 2, 0): False,
        (None, 2, 1): False,
        (None, 2, 3): False,
        (None, 2, None): True,
        (None, 3, 0): False,
        (None, 3, 1): False,
        (None, 3, 2): False,
        (None, 3, None): False,
        (None, None, 0): False,
        (None, None, 1): False,
        (None, None, 2): False,
        (None, None, 3): False,
    },
    ("ccx", "y"): False,
    ("ccx", "z"): {
        (0, None, None): True,
        (None, 0, None): True,
        (None, None, 0): False,
    },
    ("ccx", "cx"): {
        (0, 1, None): False,
        (0, None, 1): True,
        (0, None, None): True,
        (1, 0, None): False,
        (1, None, 0): False,
        (1, None, None): False,
        (None, 0, 1): True,
        (None, 0, None): True,
        (None, 1, 0): False,
        (None, 1, None): False,
        (None, None, 0): False,
        (None, None, 1): True,
    },
    ("ccx", "mcx"): {
        (0, 1, 2): False,
        (0, 1, 3): True,
        (0, 1, None): True,
        (0, 2, 1): False,
        (0, 2, 3): True,
        (0, 2, None): True,
        (0, 3, 1): False,
        (0, 3, 2): False,
        (0, 3, None): False,
        (0, None, 1): False,
        (0, None, 2): False,
        (0, None, 3): True,
        (0, None, None): True,
        (1, 0, 2): False,
        (1, 0, 3): True,
        (1, 0, None): True,
        (1, 2, 0): False,
        (1, 2, 3): True,
        (1, 2, None): True,
        (1, 3, 0): False,
        (1, 3, 2): False,
        (1, 3, None): False,
        (1, None, 0): False,
        (1, None, 2): False,
        (1, None, 3): True,
        (1, None, None): True,
        (2, 0, 1): False,
        (2, 0, 3): True,
        (2, 0, None): True,
        (2, 1, 0): False,
        (2, 1, 3): True,
        (2, 1, None): True,
        (2, 3, 0): False,
        (2, 3, 1): False,
        (2, 3, None): False,
        (2, None, 0): False,
        (2, None, 1): False,
        (2, None, 3): True,
        (2, None, None): True,
        (3, 0, 1): False,
        (3, 0, 2): False,
        (3, 0, None): False,
        (3, 1, 0): False,
        (3, 1, 2): False,
        (3, 1, None): False,
        (3, 2, 0): False,
        (3, 2, 1): False,
        (3, 2, None): False,
        (3, None, 0): False,
        (3, None, 1): False,
        (3, None, 2): False,
        (3, None, None): False,
        (None, 0, 1): False,
        (None, 0, 2): False,
        (None, 0, 3): True,
        (None, 0, None): True,
        (None, 1, 0): False,
        (None, 1, 2): False,
        (None, 1, 3): True,
        (None, 1, None): True,
        (None, 2, 0): False,
        (None, 2, 1): False,
        (None, 2, 3): True,
        (None, 2, None): True,
        (None, 3, 0): False,
        (None, 3, 1): False,
        (None, 3, 2): False,
        (None, 3, None): False,
        (None, None, 0): False,
        (None, None, 1): False,
        (None, None, 2): False,
        (None, None, 3): True,
    },
    ("ccx", "cy"): {
        (0, 1, None): False,
        (0, None, 1): False,
        (0, None, None): True,
        (1, 0, None): False,
        (1, None, 0): False,
        (1, None, None): False,
        (None, 0, 1): False,
        (None, 0, None): True,
        (None, 1, 0): False,
        (None, 1, None): False,
        (None, None, 0): False,
        (None, None, 1): False,
    },
    ("mcx", "rcccx"): {
        (0, 1, 2, 3): False,
        (0, 1, 2, None): True,
        (0, 1, 3, 2): False,
        (0, 1, 3, None): False,
        (0, 1, None, 2): False,
        (0, 1, None, 3): False,
        (0, 1, None, None): True,
        (0, 2, 1, 3): False,
        (0, 2, 1, None): True,
        (0, 2, 3, 1): False,
        (0, 2, 3, None): False,
        (0, 2, None, 1): False,
        (0, 2, None, 3): False,
        (0, 2, None, None): True,
        (0, 3, 1, 2): False,
        (0, 3, 1, None): False,
        (0, 3, 2, 1): False,
        (0, 3, 2, None): False,
        (0, 3, None, 1): False,
        (0, 3, None, 2): False,
        (0, 3, None, None): False,
        (0, None, 1, 2): False,
        (0, None, 1, 3): False,
        (0, None, 1, None): True,
        (0, None, 2, 1): False,
        (0, None, 2, 3): False,
        (0, None, 2, None): True,
        (0, None, 3, 1): False,
        (0, None, 3, 2): False,
        (0, None, 3, None): False,
        (0, None, None, 1): False,
        (0, None, None, 2): False,
        (0, None, None, 3): False,
        (0, None, None, None): True,
        (1, 0, 2, 3): False,
        (1, 0, 2, None): True,
        (1, 0, 3, 2): False,
        (1, 0, 3, None): False,
        (1, 0, None, 2): False,
        (1, 0, None, 3): False,
        (1, 0, None, None): True,
        (1, 2, 0, 3): False,
        (1, 2, 0, None): True,
        (1, 2, 3, 0): False,
        (1, 2, 3, None): False,
        (1, 2, None, 0): False,
        (1, 2, None, 3): False,
        (1, 2, None, None): True,
        (1, 3, 0, 2): False,
        (1, 3, 0, None): False,
        (1, 3, 2, 0): False,
        (1, 3, 2, None): False,
        (1, 3, None, 0): False,
        (1, 3, None, 2): False,
        (1, 3, None, None): False,
        (1, None, 0, 2): False,
        (1, None, 0, 3): False,
        (1, None, 0, None): True,
        (1, None, 2, 0): False,
        (1, None, 2, 3): False,
        (1, None, 2, None): True,
        (1, None, 3, 0): False,
        (1, None, 3, 2): False,
        (1, None, 3, None): False,
        (1, None, None, 0): False,
        (1, None, None, 2): False,
        (1, None, None, 3): False,
        (1, None, None, None): True,
        (2, 0, 1, 3): False,
        (2, 0, 1, None): True,
        (2, 0, 3, 1): False,
        (2, 0, 3, None): False,
        (2, 0, None, 1): False,
        (2, 0, None, 3): False,
        (2, 0, None, None): True,
        (2, 1, 0, 3): False,
        (2, 1, 0, None): True,
        (2, 1, 3, 0): False,
        (2, 1, 3, None): False,
        (2, 1, None, 0): False,
        (2, 1, None, 3): False,
        (2, 1, None, None): True,
        (2, 3, 0, 1): False,
        (2, 3, 0, None): False,
        (2, 3, 1, 0): False,
        (2, 3, 1, None): False,
        (2, 3, None, 0): False,
        (2, 3, None, 1): False,
        (2, 3, None, None): False,
        (2, None, 0, 1): False,
        (2, None, 0, 3): False,
        (2, None, 0, None): True,
        (2, None, 1, 0): False,
        (2, None, 1, 3): False,
        (2, None, 1, None): True,
        (2, None, 3, 0): False,
        (2, None, 3, 1): False,
        (2, None, 3, None): False,
        (2, None, None, 0): False,
        (2, None, None, 1): False,
        (2, None, None, 3): False,
        (2, None, None, None): True,
        (3, 0, 1, 2): False,
        (3, 0, 1, None): False,
        (3, 0, 2, 1): False,
        (3, 0, 2, None): False,
        (3, 0, None, 1): False,
        (3, 0, None, 2): False,
        (3, 0, None, None): False,
        (3, 1, 0, 2): False,
        (3, 1, 0, None): False,
        (3, 1, 2, 0): False,
        (3, 1, 2, None): False,
        (3, 1, None, 0): False,
        (3, 1, None, 2): False,
        (3, 1, None, None): False,
        (3, 2, 0, 1): False,
        (3, 2, 0, None): False,
        (3, 2, 1, 0): False,
        (3, 2, 1, None): False,
        (3, 2, None, 0): False,
        (3, 2, None, 1): False,
        (3, 2, None, None): False,
        (3, None, 0, 1): False,
        (3, None, 0, 2): False,
        (3, None, 0, None): False,
        (3, None, 1, 0): False,
        (3, None, 1, 2): False,
        (3, None, 1, None): False,
        (3, None, 2, 0): False,
        (3, None, 2, 1): False,
        (3, None, 2, None): False,
        (3, None, None, 0): False,
        (3, None, None, 1): False,
        (3, None, None, 2): False,
        (3, None, None, None): False,
        (None, 0, 1, 2): False,
        (None, 0, 1, 3): False,
        (None, 0, 1, None): True,
        (None, 0, 2, 1): False,
        (None, 0, 2, 3): False,
        (None, 0, 2, None): True,
        (None, 0, 3, 1): False,
        (None, 0, 3, 2): False,
        (None, 0, 3, None): False,
        (None, 0, None, 1): False,
        (None, 0, None, 2): False,
        (None, 0, None, 3): False,
        (None, 0, None, None): True,
        (None, 1, 0, 2): False,
        (None, 1, 0, 3): False,
        (None, 1, 0, None): True,
        (None, 1, 2, 0): False,
        (None, 1, 2, 3): False,
        (None, 1, 2, None): True,
        (None, 1, 3, 0): False,
        (None, 1, 3, 2): False,
        (None, 1, 3, None): False,
        (None, 1, None, 0): False,
        (None, 1, None, 2): False,
        (None, 1, None, 3): False,
        (None, 1, None, None): True,
        (None, 2, 0, 1): False,
        (None, 2, 0, 3): False,
        (None, 2, 0, None): True,
        (None, 2, 1, 0): False,
        (None, 2, 1, 3): False,
        (None, 2, 1, None): True,
        (None, 2, 3, 0): False,
        (None, 2, 3, 1): False,
        (None, 2, 3, None): False,
        (None, 2, None, 0): False,
        (None, 2, None, 1): False,
        (None, 2, None, 3): False,
        (None, 2, None, None): True,
        (None, 3, 0, 1): False,
        (None, 3, 0, 2): False,
        (None, 3, 0, None): False,
        (None, 3, 1, 0): False,
        (None, 3, 1, 2): False,
        (None, 3, 1, None): False,
        (None, 3, 2, 0): False,
        (None, 3, 2, 1): False,
        (None, 3, 2, None): False,
        (None, 3, None, 0): False,
        (None, 3, None, 1): False,
        (None, 3, None, 2): False,
        (None, 3, None, None): False,
        (None, None, 0, 1): False,
        (None, None, 0, 2): False,
        (None, None, 0, 3): False,
        (None, None, 0, None): True,
        (None, None, 1, 0): False,
        (None, None, 1, 2): False,
        (None, None, 1, 3): False,
        (None, None, 1, None): True,
        (None, None, 2, 0): False,
        (None, None, 2, 1): False,
        (None, None, 2, 3): False,
        (None, None, 2, None): True,
        (None, None, 3, 0): False,
        (None, None, 3, 1): False,
        (None, None, 3, 2): False,
        (None, None, 3, None): False,
        (None, None, None, 0): False,
        (None, None, None, 1): False,
        (None, None, None, 2): False,
        (None, None, None, 3): False,
    },
    ("cswap", "tdg"): {
        (0, None, None): True,
        (None, 0, None): False,
        (None, None, 0): False,
    },
    ("cswap", "s"): {
        (0, None, None): True,
        (None, 0, None): False,
        (None, None, 0): False,
    },
    ("cswap", "id"): True,
    ("cswap", "sx"): False,
    ("cswap", "sxdg"): False,
    ("cswap", "x"): False,
    ("cswap", "rccx"): {
        (0, 1, 2): False,
        (0, 1, None): False,
        (0, 2, 1): False,
        (0, 2, None): False,
        (0, None, 1): False,
        (0, None, 2): False,
        (0, None, None): True,
        (1, 0, 2): False,
        (1, 0, None): False,
        (1, 2, 0): False,
        (1, 2, None): False,
        (1, None, 0): False,
        (1, None, 2): False,
        (1, None, None): True,
        (2, 0, 1): False,
        (2, 0, None): False,
        (2, 1, 0): False,
        (2, 1, None): False,
        (2, None, 0): False,
        (2, None, 1): False,
        (2, None, None): False,
        (None, 0, 1): False,
        (None, 0, 2): False,
        (None, 0, None): False,
        (None, 1, 0): False,
        (None, 1, 2): False,
        (None, 1, None): False,
        (None, 2, 0): False,
        (None, 2, 1): False,
        (None, 2, None): False,
        (None, None, 0): False,
        (None, None, 1): False,
        (None, None, 2): False,
    },
    ("cswap", "rcccx"): {
        (0, 1, 2): False,
        (0, 1, 3): False,
        (0, 1, None): False,
        (0, 2, 1): False,
        (0, 2, 3): False,
        (0, 2, None): False,
        (0, 3, 1): False,
        (0, 3, 2): False,
        (0, 3, None): False,
        (0, None, 1): False,
        (0, None, 2): False,
        (0, None, 3): False,
        (0, None, None): True,
        (1, 0, 2): False,
        (1, 0, 3): False,
        (1, 0, None): False,
        (1, 2, 0): False,
        (1, 2, 3): False,
        (1, 2, None): False,
        (1, 3, 0): False,
        (1, 3, 2): False,
        (1, 3, None): False,
        (1, None, 0): False,
        (1, None, 2): False,
        (1, None, 3): False,
        (1, None, None): True,
        (2, 0, 1): True,
        (2, 0, 3): False,
        (2, 0, None): False,
        (2, 1, 0): True,
        (2, 1, 3): False,
        (2, 1, None): False,
        (2, 3, 0): False,
        (2, 3, 1): False,
        (2, 3, None): False,
        (2, None, 0): False,
        (2, None, 1): False,
        (2, None, 3): False,
        (2, None, None): True,
        (3, 0, 1): True,
        (3, 0, 2): False,
        (3, 0, None): False,
        (3, 1, 0): True,
        (3, 1, 2): False,
        (3, 1, None): False,
        (3, 2, 0): False,
        (3, 2, 1): False,
        (3, 2, None): False,
        (3, None, 0): False,
        (3, None, 1): False,
        (3, None, 2): False,
        (3, None, None): False,
        (None, 0, 1): True,
        (None, 0, 2): False,
        (None, 0, 3): False,
        (None, 0, None): False,
        (None, 1, 0): True,
        (None, 1, 2): False,
        (None, 1, 3): False,
        (None, 1, None): False,
        (None, 2, 0): False,
        (None, 2, 1): False,
        (None, 2, 3): False,
        (None, 2, None): False,
        (None, 3, 0): False,
        (None, 3, 1): False,
        (None, 3, 2): False,
        (None, 3, None): False,
        (None, None, 0): False,
        (None, None, 1): False,
        (None, None, 2): False,
        (None, None, 3): False,
    },
    ("cswap", "ecr"): False,
    ("cswap", "y"): False,
    ("cswap", "z"): {
        (0, None, None): True,
        (None, 0, None): False,
        (None, None, 0): False,
    },
    ("cswap", "cx"): {
        (0, 1, None): False,
        (0, None, 1): False,
        (0, None, None): True,
        (1, 0, None): False,
        (1, None, 0): False,
        (1, None, None): False,
        (None, 0, 1): False,
        (None, 0, None): False,
        (None, 1, 0): False,
        (None, 1, None): False,
        (None, None, 0): False,
        (None, None, 1): False,
    },
    ("cswap", "ccx"): {
        (0, 1, 2): False,
        (0, 1, None): False,
        (0, 2, 1): False,
        (0, 2, None): False,
        (0, None, 1): False,
        (0, None, 2): False,
        (0, None, None): True,
        (1, 0, 2): False,
        (1, 0, None): False,
        (1, 2, 0): False,
        (1, 2, None): False,
        (1, None, 0): False,
        (1, None, 2): False,
        (1, None, None): True,
        (2, 0, 1): True,
        (2, 0, None): False,
        (2, 1, 0): True,
        (2, 1, None): False,
        (2, None, 0): False,
        (2, None, 1): False,
        (2, None, None): False,
        (None, 0, 1): True,
        (None, 0, 2): False,
        (None, 0, None): False,
        (None, 1, 0): True,
        (None, 1, 2): False,
        (None, 1, None): False,
        (None, 2, 0): False,
        (None, 2, 1): False,
        (None, 2, None): False,
        (None, None, 0): False,
        (None, None, 1): False,
        (None, None, 2): False,
    },
    ("cswap", "mcx"): {
        (0, 1, 2): True,
        (0, 1, 3): False,
        (0, 1, None): False,
        (0, 2, 1): True,
        (0, 2, 3): False,
        (0, 2, None): False,
        (0, 3, 1): False,
        (0, 3, 2): False,
        (0, 3, None): False,
        (0, None, 1): False,
        (0, None, 2): False,
        (0, None, 3): False,
        (0, None, None): True,
        (1, 0, 2): True,
        (1, 0, 3): False,
        (1, 0, None): False,
        (1, 2, 0): True,
        (1, 2, 3): False,
        (1, 2, None): False,
        (1, 3, 0): False,
        (1, 3, 2): False,
        (1, 3, None): False,
        (1, None, 0): False,
        (1, None, 2): False,
        (1, None, 3): False,
        (1, None, None): True,
        (2, 0, 1): True,
        (2, 0, 3): False,
        (2, 0, None): False,
        (2, 1, 0): True,
        (2, 1, 3): False,
        (2, 1, None): False,
        (2, 3, 0): False,
        (2, 3, 1): False,
        (2, 3, None): False,
        (2, None, 0): False,
        (2, None, 1): False,
        (2, None, 3): False,
        (2, None, None): True,
        (3, 0, 1): True,
        (3, 0, 2): True,
        (3, 0, None): False,
        (3, 1, 0): True,
        (3, 1, 2): True,
        (3, 1, None): False,
        (3, 2, 0): True,
        (3, 2, 1): True,
        (3, 2, None): False,
        (3, None, 0): False,
        (3, None, 1): False,
        (3, None, 2): False,
        (3, None, None): False,
        (None, 0, 1): True,
        (None, 0, 2): True,
        (None, 0, 3): False,
        (None, 0, None): False,
        (None, 1, 0): True,
        (None, 1, 2): True,
        (None, 1, 3): False,
        (None, 1, None): False,
        (None, 2, 0): True,
        (None, 2, 1): True,
        (None, 2, 3): False,
        (None, 2, None): False,
        (None, 3, 0): False,
        (None, 3, 1): False,
        (None, 3, 2): False,
        (None, 3, None): False,
        (None, None, 0): False,
        (None, None, 1): False,
        (None, None, 2): False,
        (None, None, 3): False,
    },
    ("cswap", "cy"): {
        (0, 1, None): False,
        (0, None, 1): False,
        (0, None, None): True,
        (1, 0, None): False,
        (1, None, 0): False,
        (1, None, None): False,
        (None, 0, 1): False,
        (None, 0, None): False,
        (None, 1, 0): False,
        (None, 1, None): False,
        (None, None, 0): False,
        (None, None, 1): False,
    },
    ("cy", "rcccx"): {
        (0, 1): False,
        (0, 2): False,
        (0, 3): False,
        (0, None): True,
        (1, 0): False,
        (1, 2): False,
        (1, 3): False,
        (1, None): True,
        (2, 0): False,
        (2, 1): False,
        (2, 3): True,
        (2, None): True,
        (3, 0): False,
        (3, 1): False,
        (3, 2): False,
        (3, None): False,
        (None, 0): False,
        (None, 1): False,
        (None, 2): False,
        (None, 3): False,
    },
    ("cy", "mcx"): {
        (0, 1): False,
        (0, 2): False,
        (0, 3): False,
        (0, None): True,
        (1, 0): False,
        (1, 2): False,
        (1, 3): False,
        (1, None): True,
        (2, 0): False,
        (2, 1): False,
        (2, 3): False,
        (2, None): True,
        (3, 0): False,
        (3, 1): False,
        (3, 2): False,
        (3, None): False,
        (None, 0): False,
        (None, 1): False,
        (None, 2): False,
        (None, 3): False,
    },
    ("cz", "tdg"): True,
    ("cz", "s"): True,
    ("cz", "h"): False,
    ("cz", "id"): True,
    ("cz", "sx"): False,
    ("cz", "sxdg"): False,
    ("cz", "x"): False,
    ("cz", "rccx"): {
        (0, 1): True,
        (0, 2): False,
        (0, None): True,
        (1, 0): True,
        (1, 2): False,
        (1, None): True,
        (2, 0): False,
        (2, 1): False,
        (2, None): False,
        (None, 0): True,
        (None, 1): True,
        (None, 2): False,
    },
    ("cz", "rcccx"): {
        (0, 1): True,
        (0, 2): True,
        (0, 3): False,
        (0, None): True,
        (1, 0): True,
        (1, 2): True,
        (1, 3): False,
        (1, None): True,
        (2, 0): True,
        (2, 1): True,
        (2, 3): False,
        (2, None): True,
        (3, 0): False,
        (3, 1): False,
        (3, 2): False,
        (3, None): False,
        (None, 0): True,
        (None, 1): True,
        (None, 2): True,
        (None, 3): False,
    },
    ("cz", "ecr"): False,
    ("cz", "y"): False,
    ("cz", "z"): True,
    ("cz", "cx"): {
        (0, 1): False,
        (0, None): True,
        (1, 0): False,
        (1, None): False,
        (None, 0): True,
        (None, 1): False,
    },
    ("cz", "ccx"): {
        (0, 1): True,
        (0, 2): False,
        (0, None): True,
        (1, 0): True,
        (1, 2): False,
        (1, None): True,
        (2, 0): False,
        (2, 1): False,
        (2, None): False,
        (None, 0): True,
        (None, 1): True,
        (None, 2): False,
    },
    ("cz", "mcx"): {
        (0, 1): True,
        (0, 2): True,
        (0, 3): False,
        (0, None): True,
        (1, 0): True,
        (1, 2): True,
        (1, 3): False,
        (1, None): True,
        (2, 0): True,
        (2, 1): True,
        (2, 3): False,
        (2, None): True,
        (3, 0): False,
        (3, 1): False,
        (3, 2): False,
        (3, None): False,
        (None, 0): True,
        (None, 1): True,
        (None, 2): True,
        (None, 3): False,
    },
    ("cz", "cswap"): {
        (0, 1): False,
        (0, 2): False,
        (0, None): True,
        (1, 0): False,
        (1, 2): True,
        (1, None): False,
        (2, 0): False,
        (2, 1): True,
        (2, None): False,
        (None, 0): True,
        (None, 1): False,
        (None, 2): False,
    },
    ("cz", "cy"): {
        (0, 1): False,
        (0, None): True,
        (1, 0): False,
        (1, None): False,
        (None, 0): True,
        (None, 1): False,
    },
}
